In [1]:
#Импортируем библиотеки
import numpy as np
import pandas as pd
import copy
import re
import openpyxl

In [2]:
# Читаем таблицу 2021.
df = pd.read_csv("C:/Users/NightMare/Desktop/YandexHack/2020_new.csv", encoding='Windows-1251')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Год сметы                   251 non-null    int64
 1   Смета                       251 non-null    object
 2   Подразделение БР            251 non-null    object
 3   Код вида расходов           251 non-null    object
 4   Наименование вида расходов  251 non-null    object
 5   Направление расходов        251 non-null    object
 6   Конечный остаток            251 non-null    float64
 7   Дата проведения             251 non-null    object
 8   Дата проведения (день)      251 non-null    float64
 9   Дата проведения (месяц)     251 non-null    float64
 10  Дата проведения (год)       251 non-null    float64
dtypes: float64(4), int64(1), object(6)
memory usage: 21.7+ KB

In [4]:
df.head()

,Год сметы,Смета,Подразделение БР,Код вида расходов,Наименование вида расходов,Направление расходов,Конечный остаток,Дата проведения,Дата проведения (день),Дата проведения (месяц),Дата проведения (год)
0,2020,Хозяйственно-эксплуатационное направление ДГУ,Дальневосточное главное управление Центральног...,134.1100.010000,Расходы по оплате потребления электроэнергии,134.1100.010000 Плата за технологическое присо...,32790.96,2020-12-31,31.0,12.0,2020.0
1,2020,Хозяйственно-эксплуатационное направление ДГУ,Дальневосточное главное управление Центральног...,134.1100.010000,Расходы по оплате потребления электроэнергии,Оплата за электроэнергию по тарифам зд. Вл-А...,2274.13,2020-12-31,31.0,12.0,2020.0
2,2020,Хозяйственно-эксплуатационное направление ДГУ,Дальневосточное главное управление Центральног...,134.1100.010000,Расходы по оплате потребления электроэнергии,Оплата за электроэнергию по тарифам зд. ул.Све...,238482.63,2020-12-31,31.0,12.0,2020.0
3,2020,Хозяйственно-эксплуатационное направление ДГУ,Дальневосточное главное управление Центральног...,134.1100.010000,Расходы по оплате потребления электроэнергии,Оплата за электроэнергию по тарифам зд. г.Нахо...,614813.95,2020-12-31,31.0,12.0,2020.0
4,2020,Хозяйственно-эксплуатационное направление ДГУ,Дальневосточное главное управление Центральног...,134.1100.010000,Расходы по оплате потребления электроэнергии,Оплата за электроэнергию по тарифам зд. Склад...,22413.58,2020-12-31,31.0,12.0,2020.0

In [5]:
df['Дата проведения (день)'] = df['Дата проведения (день)'].astype(int)
df['Дата проведения (месяц)'] = df['Дата проведения (месяц)'].astype(int)
df['Дата проведения (год)'] = df['Дата проведения (год)'].astype(int)

#Удаление элементов содержащих nan
print(len(df['Дата проведения (день)']))
for i in range(len(df['Дата проведения (день)'])):
    cell = df['Дата проведения (день)'][i]
    if pd.isnull(cell) == True:
        df = df.drop(i,axis=0)

print(len(df['Дата проведения (день)']))

# Выкидываем дату проведения.
df = df.drop(['Дата проведения', 'Смета', 'Год сметы', 'Подразделение БР', 'Код вида расходов'], axis=1)

def merge_columns(df, col1, col2, col3, new_col):
    df[new_col] = df[col1].astype(str) + '.' + df[col2].astype(str) + '.' + df[col3].astype(str)
    return df

df = merge_columns(df, 'Дата проведения (день)', 'Дата проведения (месяц)', 'Дата проведения (год)', 'Дата проведения')

def format_date_column(df, date_column):
    df[date_column] = pd.to_datetime(df[date_column], format='%d.%m.%Y').dt.strftime('%d.%m.%Y')
    return df

df = format_date_column(df, 'Дата проведения')

# Выкидываем дату проведения.
df = df.drop(['Дата проведения (день)', 'Дата проведения (месяц)', 'Дата проведения (год)'], axis=1)

df.head()

251
251

,Наименование вида расходов,Направление расходов,Конечный остаток,Дата проведения
0,Расходы по оплате потребления электроэнергии,134.1100.010000 Плата за технологическое присо...,32790.96,31.12.2020
1,Расходы по оплате потребления электроэнергии,Оплата за электроэнергию по тарифам зд. Вл-А...,2274.13,31.12.2020
2,Расходы по оплате потребления электроэнергии,Оплата за электроэнергию по тарифам зд. ул.Све...,238482.63,31.12.2020
3,Расходы по оплате потребления электроэнергии,Оплата за электроэнергию по тарифам зд. г.Нахо...,614813.95,31.12.2020
4,Расходы по оплате потребления электроэнергии,Оплата за электроэнергию по тарифам зд. Склад...,22413.58,31.12.2020

In [6]:
# Переносим Конечный остаток вправо.
new_order = [col for col in df.columns if col != 'Конечный остаток'] + ['Конечный остаток']
df = df[new_order]

In [7]:
df.head()

,Наименование вида расходов,Направление расходов,Дата проведения,Конечный остаток
0,Расходы по оплате потребления электроэнергии,134.1100.010000 Плата за технологическое присо...,31.12.2020,32790.96
1,Расходы по оплате потребления электроэнергии,Оплата за электроэнергию по тарифам зд. Вл-А...,31.12.2020,2274.13
2,Расходы по оплате потребления электроэнергии,Оплата за электроэнергию по тарифам зд. ул.Све...,31.12.2020,238482.63
3,Расходы по оплате потребления электроэнергии,Оплата за электроэнергию по тарифам зд. г.Нахо...,31.12.2020,614813.95
4,Расходы по оплате потребления электроэнергии,Оплата за электроэнергию по тарифам зд. Склад...,31.12.2020,22413.58

In [8]:
# Задайте максимальную ширину столбца
pd.set_option('display.max_colwidth', None)

# Выведите данные
print(df['Направление расходов'].head(10))
type_JKY = df['Направление расходов']

0    134.1100.010000 Плата за технологическое присоединение к электрическим сетям г. Владивосток ул. Калинина,261
1                                    Оплата за электроэнергию по тарифам  зд.  Вл-Александровское, ул. Седова, 23
2                                                      Оплата за электроэнергию по тарифам зд. ул.Светланская,111
3                                        Оплата за электроэнергию по тарифам зд. г.Находка, Находкинский пр-т, 13
4                                                  Оплата за электроэнергию по тарифам  зд. Склад ул.Фонтанная,19
5                                             Оплата за электроэнергию по тарифам  зд. Убежище ул.Семеновская,29а
6                                                        Оплата за электроэнергию по тарифам  зд. ул.Калинина,261
7                                                         Оплата за электроэнергию по тарифам зд. ул.Мордовцева,6
8                                                       Оплата за электроэнергию по тарифам зд. ул.Светланская,69
9                                                       Оплата за электроэнергию по тарифам зд. ул.Светланская,71
Name: Направление расходов, dtype: object

In [9]:
pd.set_option('display.max_colwidth', None)

def process_substring(value, substring):
    if substring in value:
        new_value = value.split(substring, 1)[1].strip()
        return new_value
    return value

substrings_to_process = [
    'зд. ',
    'зд.',
    'здание',
    'по тарифам  ',
    'по тарифам ',
    'по тарифам,',
    'ул.',
    'ул. ',
    'г.',
    'с.',
    
]

for substring in substrings_to_process:
    df['Направление расходов'] = df['Направление расходов'].apply(lambda x: process_substring(x, substring))

def remove_suffix_from_column(column, suffix):
    # Создаем новый список для хранения строк без суффикса
    new_column = []

    # Перебираем каждую строку в столбце
    for row in column:
        # Проверяем, заканчивается ли текущая строка на заданный суффикс
        if row.endswith(suffix):
            # Если да, удаляем суффикс и добавляем строку в новый список
            new_row = row[:-len(suffix)]
            new_column.append(new_row)
        else:
            # Если нет, просто добавляем строку в новый список
            new_column.append(row)

    return new_column

suffixes_to_remove = [
    "-  ст.134.1100",
    " ст.134.1100",
    "-",
    " -",
    ",",
    "- ",
    "- ст. 134.1100",
    " -  ",
    ", "
    "Здание ",
    " -ст.134.1100",
    ". Здание ",
    "-ст.134.1100",
    " ст. 134.1100",
    "-ст.1341100",
    "ст.134.1100"
]

for suffix in suffixes_to_remove:
    df['Направление расходов'] = remove_suffix_from_column(df['Направление расходов'], suffix)
    
# Выведите уникальные значения
for value in df['Направление расходов'].unique():
    print(value)

Калинина,261
Седова, 23
Светланская,111
Находка, Находкинский пр-т, 13
Фонтанная,19
Семеновская,29а
Мордовцева,6
Светланская,69
Светланская,71
Светланская,71 Пристройка
Светланская,73
Светланская,73А
Океанский пр-т, 34
Пушкинская, 8Б
Некрасова, 102
Пушкина,59
Ленина, 64
Находка, Находкинский пр-т,13
Некрасова, 102 ( гараж на 10 а/м)
)
Калинина, 261
Пушкинская,8б
Светланская,71-Пристройка
Светланская,73А
Фонтанная, 19
пр-т 50 лет Октября,89
Ленина,64
Некрасова, 102 (ГАРАЖ на 10 автомобилей)
Пушкина, 59
Мордовцева, 6
Светланская, 69
Светланская, 71
Светланская, 71 Пристройка
Светланская, 73 А
Фонтанная, 19
Некрасова,102
Некрасова,102 (ГАРАЖ на 10 автомобилей)
Другие расходы прошлых лет, выявленные в текущем году. Расходы на коммунальные услуги
Горького 7 дизель-генераторная установка
Дежнева, 7
Южная (гараж)
Горького 7
Колхозная 32 Б (склад)
п. Эгвекинот
Билибино
Горького, 7
Дежнева 7
Колхозная 32 Б
пгт.Эгвекинот
Южная
пгт. Эгвекинот
Биробиджан, пр-т 60-летия СССР, 5
Чапаева,5А
Чапаева, 5А

Богдана Хмельницкого 52/2
Профсоюзная, д.12
Ленина, 29
(Пристройка)
Благовещенск, пер.Святителя Иннокентия, 17, Пристройка к зданию (Новая)
Благовещенск, пер.Святителя Иннокентия, 17, Гараж
Благовещенск, пер.Святителя Иннокентия, 17, Помещение Объект №2
Зея пер.Жуковский,15, Гараж
Благовещенск, пер. Святителя Иннокентия,17, Гараж
Благовещенск, пер. Святителя Иннокентия,17, Помещение объект №2
Благовещенск, пер. Святителя Иннокентия,17, Пристройка к зданию (Новая)
Богдана Хмельницкого 52/2, Контрольно-пропускной пункт
Профсоюзная, 12
Ленина 29
Зея, пер.Жуковский,15, Гараж
Благовещенск, пер.Святителя Иннокентия, 17, Пристройка к зданию (новая)
Богдана Хмельницкого, 52/2, Контрольно-пропускной пункт
Профсоюзная,12
Пушкина, 4
Пушкина,6 (Гараж)
К.Маркса,36-20, кв.29
К.Маркса 36-20, кв.29
Поротова, 14
Ленинская, 33
Партизанская, 11
Ленинская, 22
пр. Карла Маркса, 29/2
пр. К/Маркса 29/2
Ленинская 22
РКЦ Комсомольск-на-Амуре, пр. Первостроителей, 19
Советская, 26
Воронежская, 154
М-Амурского, 42
М-Амурского, 21
Калинина, 95
ул, Воронежская, 154
М- Амурского, 21
М- Амурского, 42
Советская, 27
РКЦ Комсомольск-на-Амуре,пр. Первостроителей, 19
Комсомольск -на- Амуре, пр. Первостроителей, 19
Южно-Сахалинск, Коммунистический пр-т, д. 47
Карла Маркса, д. 16
Расходы по оплате потребления электроэнергии РКЦ Курильск
Расходы по оплате отопления РКЦ Курильск
Расходы по приобретению дизельного топлива (отопление) РКЦ Курильск
Расходы по оплате водоотведения РКЦ Курильск
Расходы по оплате холодного водоснабжения РКЦ Курильск
Кирова,17
50 лет Советской Армии, 31/7
Покровск
Ленина, 70
РКЦ Нерюнгри
Ленина, 22
Ленина,70
Кирова, 17
Светланская, 71 (Буфет)
Светланская, 73 (Столовая)
Светланская,73 (столовая)
Светланская,71 (буфет)
Светланская, 73  (Столовая)
Верхнепортовая, 44
Оплата за электроэнергию по тарифам
Оплата за водоотведение по тарифам
Оплата за холодное водоснабжение по тарифам
Муравьева-Амурского, 21
Муравьева-Амурского, 42

In [10]:
len(df['Направление расходов'])

251

In [11]:
df.insert(loc=df.columns.get_loc('Направление расходов') + 1, column='Вид объекта', value=0)
df.head()

,Наименование вида расходов,Направление расходов,Вид объекта,Дата проведения,Конечный остаток
0,Расходы по оплате потребления электроэнергии,"Калинина,261",0,31.12.2020,32790.96
1,Расходы по оплате потребления электроэнергии,"Седова, 23",0,31.12.2020,2274.13
2,Расходы по оплате потребления электроэнергии,"Светланская,111",0,31.12.2020,238482.63
3,Расходы по оплате потребления электроэнергии,"Находка, Находкинский пр-т, 13",0,31.12.2020,614813.95
4,Расходы по оплате потребления электроэнергии,"Фонтанная,19",0,31.12.2020,22413.58

In [12]:
def compare_and_assign(df, column_name, replacements):
    for index, value in df[column_name].items():
        for replacement in replacements:
            target_string = replacement['target']
            new_value = replacement['new_value']
            # Удаляем пробелы с обеих сторон строки перед проверкой
            if value.rstrip().endswith(target_string):
                df.at[index, "Вид объекта"] = new_value
                # Удаляем target строку из строки с которой сравнивали
                df.at[index, column_name] = value.replace(target_string, '').strip()
    return df[column_name]  # Возвращаем измененный столбец

# Заменяем значения, оканчивающиеся на "(Буфет)"
replacements = [
    {'target': '(Буфет)', 'new_value': 'буфет'},
    {'target': '(Столовая)', 'new_value': 'столовая'},
    {'target': '(ГАРАЖ на 10 автомобилей)', 'new_value': 'большой гараж'},
    {'target': 'Пристройка', 'new_value': 'пристройка'},
    {'target': '( гараж на 10 а/м)', 'new_value': 'большой гараж'},
    {'target': ', Административное (Пристройка)', 'new_value': 'пристройка'},\
    {'target': ', Пристройка к зданию (Новая)', 'new_value': 'пристройка'},
    {'target': ', Помещение объект № 2', 'new_value': 'помещение'},
    {'target': ', Помещение объект №2', 'new_value': 'помещение'},
    {'target': ', Пристройка к зданию (новая)', 'new_value': 'пристройка к зданию'},
    {'target': ', Контрольно-пропускной пункт', 'new_value': 'КПП'},
    {'target': ', Гараж', 'new_value': 'гараж'},
    {'target': ' (гараж)', 'new_value': 'гараж'},
    {'target': ' (жилой подъезд)', 'new_value': 'жилой подъезд'},
    {'target': ' (функц. помещение)', 'new_value': 'функц. помещение'},
    {'target': ' (жилая часть)', 'new_value': 'жилая часть'},
    {'target': ' (шахтн. канализац. станция)', 'new_value': 'шахтн. канализац. станция'},
    {'target': '-', 'new_value': ''},
    {'target': 'дизель-генераторная установка', 'new_value': 'генератор'},
    {'target': '(склад)', 'new_value': 'склад'},
    {'target': '(буфет)', 'new_value': 'буфет'},
    {'target': '(столовая)', 'new_value': 'столовая'},
    {'target': '(Гараж)', 'new_value': 'гараж'},
    {'target': ', Помещение Объект №2', 'new_value': 'помещение'}
]
df['Направление расходов'] = compare_and_assign(df, 'Направление расходов', replacements)

def compare_and_assign_prefix(df, column_name, replacements):
    for index, value in df[column_name].items():
        for replacement in replacements:
            target_string = replacement['target']
            new_value = replacement['new_value']
            # Удаляем пробелы с обеих сторон строки перед проверкой
            if value.lstrip().startswith(target_string):
                df.at[index, "Вид объекта"] = new_value
                # Удаляем target строку из строки с которой сравнивали
                df.at[index, column_name] = value.replace(target_string, '', 1).strip()
    return df[column_name]  # Возвращаем измененный столбец

replacements = [
    {'target': '(Гараж)  ', 'new_value': 'гараж'},
    {'target': 'Оплата за электроэнергию по тарифам', 'new_value': ''},
    {'target': 'Оплата за водоотведение по тарифам', 'new_value': ''},
    {'target': 'Оплата за холодное водоснабжение по тарифам', 'new_value': ''},
    {'target': 'Расходы по оплате холодного водоснабжения ', 'new_value': ''},
    {'target': 'Расходы по оплате водоотведения ', 'new_value': ''},
    {'target': 'Расходы по оплате холодного водоснабжения ', 'new_value': ''},
    {'target': 'Расходы по приобретению дизельного топлива (отопление) ', 'new_value': ''},
    {'target': 'Расходы по оплате отопления ', 'new_value': ''},
    {'target': 'Расходы по оплате потребления электроэнергии ', 'new_value': ''},
    {'target': '(Пристройка)', 'new_value': ''},
    {'target': '(склад) ', 'new_value': 'склад'},
    {'target': ', ', 'new_value': ''},
    {'target': 'Оплата за дизельное топливо ', 'new_value': ''},
    {'target': 'ст.134.1100', 'new_value': ''},
    {'target': 'Оплата за дизельное топливо  ', 'new_value': ''},
    {'target': 'ст.134.1100', 'new_value': ''},
    {'target': ' ', 'new_value': ''},
    {'target': 'Убежище ', 'new_value': 'убежище'},
    {'target': 'Склад ', 'new_value': 'склад'},
    {'target': ')   ', 'new_value': ''},
    {'target': ')', 'new_value': ''},
    {'target': 'Плата за технологическое присоединение к электрическим сетям (в случаях, не связанным со строительством,реконстр. и кап.ремонтом ', 'new_value': ''},
    {'target': 'Другие расходы прошлых лет, выявленные в текущем году. Расходы на коммунальные услуги', 'new_value': ''},
    
]
df['Направление расходов'] = compare_and_assign_prefix(df, 'Направление расходов', replacements)


def replace_zero_values(df, column_name, replacement_value):
    df[column_name] = df[column_name].replace(0, replacement_value)
    return df[column_name]

replacement_value = 'Здание'
df['Вид объекта'] = replace_zero_values(df, 'Вид объекта', replacement_value)

def drop_rows_with_empty_values(df):
    # Удаляем строки, содержащие хотя бы одно из значений: 0, NaN, пустую строку или пробелы
    df = df.dropna().replace({'': None, ' ': None}).dropna()
    return df

# Удаляем строки с пустыми значениями
df= drop_rows_with_empty_values(df)

# Вывод уникальных значений
for index, value in df['Направление расходов'].items():
    print(f' Адрес: {value} --------- Вид объекта: {df.at[index, "Вид объекта"]}')

 Адрес: Калинина,261 --------- Вид объекта: Здание
 Адрес: Седова, 23 --------- Вид объекта: Здание
 Адрес: Светланская,111 --------- Вид объекта: Здание
 Адрес: Находка, Находкинский пр-т, 13 --------- Вид объекта: Здание
 Адрес: Фонтанная,19 --------- Вид объекта: Здание
 Адрес: Семеновская,29а --------- Вид объекта: Здание
 Адрес: Калинина,261 --------- Вид объекта: Здание
 Адрес: Мордовцева,6 --------- Вид объекта: Здание
 Адрес: Светланская,69 --------- Вид объекта: Здание
 Адрес: Светланская,71 --------- Вид объекта: Здание
 Адрес: Светланская,71 --------- Вид объекта: пристройка
 Адрес: Светланская,73 --------- Вид объекта: Здание
 Адрес: Светланская,73А --------- Вид объекта: Здание
 Адрес: Океанский пр-т, 34 --------- Вид объекта: Здание
 Адрес: Пушкинская, 8Б --------- Вид объекта: Здание
 Адрес: Некрасова, 102 --------- Вид объекта: Здание
 Адрес: Пушкина,59 --------- Вид объекта: Здание
 Адрес: Ленина, 64 --------- Вид объекта: Здание
 Адрес: Находка, Находкинский пр-т,13 --------- Вид объекта: Здание
 Адрес: Некрасова, 102 --------- Вид объекта: большой гараж
 Адрес: Пушкина,59 --------- Вид объекта: Здание
 Адрес: Калинина, 261 --------- Вид объекта: Здание
 Адрес: Пушкинская,8б --------- Вид объекта: Здание
 Адрес: Мордовцева,6 --------- Вид объекта: Здание
 Адрес: Светланская,69 --------- Вид объекта: Здание
 Адрес: Светланская,71 --------- Вид объекта: Здание
 Адрес: Светланская,71- --------- Вид объекта: пристройка
 Адрес: Светланская,73 --------- Вид объекта: Здание
 Адрес: Светланская,73А  --------- Вид объекта: Здание
 Адрес: Фонтанная, 19  --------- Вид объекта: Здание
 Адрес: Океанский пр-т, 34 --------- Вид объекта: Здание
 Адрес: Светланская,111 --------- Вид объекта: Здание
 Адрес: пр-т 50 лет Октября,89 --------- Вид объекта: Здание
 Адрес: Ленина,64 --------- Вид объекта: Здание
 Адрес: Светланская,111 --------- Вид объекта: Здание
 Адрес: Находка, Находкинский пр-т, 13 --------- Вид объекта: Здание
 Адрес: Некрасова, 102 --------- Вид объекта: Здание
 Адрес: Некрасова, 102 --------- Вид объекта: большой гараж
 Адрес: Океанский пр-т, 34 --------- Вид объекта: Здание
 Адрес: Пушкина, 59 --------- Вид объекта: Здание
 Адрес: Калинина, 261 --------- Вид объекта: Здание
 Адрес: Мордовцева, 6 --------- Вид объекта: Здание
 Адрес: Светланская, 69 --------- Вид объекта: Здание
 Адрес: Светланская, 71 --------- Вид объекта: Здание
 Адрес: Светланская, 71 --------- Вид объекта: пристройка
 Адрес: Светланская, 73 А --------- Вид объекта: Здание
 Адрес: Фонтанная, 19 --------- Вид объекта: Здание
 Адрес: Светланская,111 --------- Вид объекта: Здание
 Адрес: Находка, Находкинский пр-т, 13 --------- Вид объекта: Здание
 Адрес: Некрасова,102 --------- Вид объекта: Здание
 Адрес: Некрасова,102 --------- Вид объекта: большой гараж
 Адрес: Океанский пр-т, 34 --------- Вид объекта: Здание
 Адрес: Пушкина,59 --------- Вид объекта: Здание
 Адрес: Калинина, 261 --------- Вид объекта: Здание
 Адрес: Мордовцева,6 --------- Вид объекта: Здание
 Адрес: Светланская, 69 --------- Вид объекта: Здание
 Адрес: Светланская, 71 --------- Вид объекта: Здание
 Адрес: Светланская, 71 --------- Вид объекта: пристройка
 Адрес: Светланская, 73 А --------- Вид объекта: Здание
 Адрес: Фонтанная, 19 --------- Вид объекта: Здание
 Адрес: Горького 7 --------- Вид объекта: генератор
 Адрес: Дежнева, 7 --------- Вид объекта: Здание
 Адрес: Южная --------- Вид объекта: гараж
 Адрес: Горького 7 --------- Вид объекта: Здание
 Адрес: Колхозная 32 Б --------- Вид объекта: склад
 Адрес: п. Эгвекинот --------- Вид объекта: Здание
 Адрес: Билибино --------- Вид объекта: Здание
 Адрес: Горького, 7 --------- Вид объекта: Здание
 Адрес: Дежнева 7 --------- Вид объекта: Здание
 Адрес: Колхозная 32 Б --------- Вид объекта: Здание
 Адрес: Южная --------- Вид объекта: гараж
 Адрес: Билибино --------- Вид объекта: Здание
 Адрес: пгт.Эгвекинот --------- Вид объекта: Здание
 Адрес: Дежнева 7 --------- Вид объекта: Здание
 Адрес: Южная --------- Вид объекта: Здание
 Адрес: Билибино --------- Вид объекта: Здание
 Адрес: пгт. Эгвекинот --------- Вид объекта: Здание
 Адрес: Южная --------- Вид объекта: Здание
 Адрес: Дежнева 7 --------- Вид объекта: Здание
 Адрес: Билибино --------- Вид объекта: Здание
 Адрес: пгт.Эгвекинот --------- Вид объекта: Здание
 Адрес: Дежнева 7 --------- Вид объекта: Здание
 Адрес: Южная --------- Вид объекта: гараж
 Адрес: Билибино --------- Вид объекта: Здание
 Адрес: пгт.Эгвекинот --------- Вид объекта: Здание
 Адрес: Биробиджан, пр-т 60-летия СССР, 5 --------- Вид объекта: Здание
 Адрес: Чапаева,5А --------- Вид объекта: Здание
 Адрес: Биробиджан, пр-т 60-летия СССР, 5 --------- Вид объекта: Здание
 Адрес: Чапаева, 5А --------- Вид объекта: Здание
 Адрес: Биробиджан, пр-т 60-летия СССР, 5 --------- Вид объекта: Здание
 Адрес: Чапаева, 5А --------- Вид объекта: Здание
 Адрес: Биробиджан, пр-т 60-летия СССР, 5 --------- Вид объекта: Здание
 Адрес: Чапаева, 5А --------- Вид объекта: Здание
 Адрес: Богдана Хмельницкого 52/2 --------- Вид объекта: Здание
 Адрес: Профсоюзная, д.12 --------- Вид объекта: Здание
 Адрес: Ленина, 29 --------- Вид объекта: Здание
 Адрес: Благовещенск, пер.Святителя Иннокентия, 17 --------- Вид объекта: пристройка
 Адрес: Благовещенск, пер.Святителя Иннокентия, 17 --------- Вид объекта: гараж
 Адрес: Благовещенск, пер.Святителя Иннокентия, 17 --------- Вид объекта: помещение
 Адрес: Зея пер.Жуковский,15 --------- Вид объекта: гараж
 Адрес: Благовещенск, пер. Святителя Иннокентия,17 --------- Вид объекта: гараж
 Адрес: Благовещенск, пер. Святителя Иннокентия,17 --------- Вид объекта: помещение
 Адрес: Благовещенск, пер. Святителя Иннокентия,17 --------- Вид объекта: пристройка
 Адрес: Богдана Хмельницкого 52/2 --------- Вид объекта: КПП
 Адрес: Профсоюзная, 12 --------- Вид объекта: Здание
 Адрес: Ленина 29 --------- Вид объекта: Здание
 Адрес: Зея, пер.Жуковский,15 --------- Вид объекта: гараж
 Адрес: Благовещенск, пер.Святителя Иннокентия, 17 --------- Вид объекта: гараж
 Адрес: Благовещенск, пер.Святителя Иннокентия, 17 --------- Вид объекта: пристройка к зданию
 Адрес: Богдана Хмельницкого, 52/2 --------- Вид объекта: КПП
 Адрес: Профсоюзная,12 --------- Вид объекта: Здание
 Адрес: Благовещенск, пер.Святителя Иннокентия, 17 --------- Вид объекта: пристройка к зданию
 Адрес: Богдана Хмельницкого, 52/2 --------- Вид объекта: КПП
 Адрес: Профсоюзная,12 --------- Вид объекта: Здание
 Адрес: Профсоюзная, 12 --------- Вид объекта: Здание
 Адрес: Пушкина, 4 --------- Вид объекта: Здание
 Адрес: Пушкина,6 --------- Вид объекта: гараж
 Адрес: Пушкина, 4 --------- Вид объекта: Здание
 Адрес: К.Маркса,36-20, кв.29 --------- Вид объекта: Здание
 Адрес: Пушкина, 4 --------- Вид объекта: Здание
 Адрес: К.Маркса 36-20, кв.29 --------- Вид объекта: Здание
 Адрес: Пушкина, 4 --------- Вид объекта: Здание
 Адрес: Пушкина, 4 --------- Вид объекта: Здание
 Адрес: Поротова, 14 --------- Вид объекта: Здание
 Адрес: Ленинская, 33 --------- Вид объекта: Здание
 Адрес: Партизанская, 11 --------- Вид объекта: Здание
 Адрес: Ленинская, 22 --------- Вид объекта: Здание
 Адрес: пр. Карла Маркса, 29/2 --------- Вид объекта: Здание
 Адрес: пр. К/Маркса 29/2 --------- Вид объекта: Здание
 Адрес: Ленинская 22 --------- Вид объекта: Здание
 Адрес: Ленинская, 33 --------- Вид объекта: Здание
 Адрес: Поротова, 14 --------- Вид объекта: Здание
 Адрес: Ленинская, 33 --------- Вид объекта: Здание
 Адрес: Партизанская, 11 --------- Вид объекта: Здание
 Адрес: Ленинская, 22 --------- Вид объекта: Здание
 Адрес: Поротова, 14 --------- Вид объекта: Здание
 Адрес: Ленинская, 33 --------- Вид объекта: Здание
 Адрес: Ленинская, 22 --------- Вид объекта: Здание
 Адрес: пр. Карла Маркса, 29/2 --------- Вид объекта: Здание
 Адрес: Ленинская, 33 --------- Вид объекта: Здание
 Адрес: Поротова, 14 --------- Вид объекта: Здание
 Адрес: Ленинская, 33 --------- Вид объекта: Здание
 Адрес: Партизанская, 11 --------- Вид объекта: Здание
 Адрес: Ленинская, 22 --------- Вид объекта: Здание
 Адрес: пр. Карла Маркса, 29/2 --------- Вид объекта: Здание
 Адрес: РКЦ Комсомольск-на-Амуре, пр. Первостроителей, 19 --------- Вид объекта: Здание
 Адрес: Советская, 26 --------- Вид объекта: Здание
 Адрес: Воронежская, 154 --------- Вид объекта: Здание
 Адрес: М-Амурского, 42 --------- Вид объекта: Здание
 Адрес: М-Амурского, 21 --------- Вид объекта: Здание
 Адрес: Калинина, 95 --------- Вид объекта: Здание
 Адрес: РКЦ Комсомольск-на-Амуре, пр. Первостроителей, 19 --------- Вид объекта: Здание
 Адрес: ул, Воронежская, 154 --------- Вид объекта: Здание
 Адрес: М- Амурского, 21 --------- Вид объекта: Здание
 Адрес: М- Амурского, 42 --------- Вид объекта: Здание
 Адрес: Советская, 26 --------- Вид объекта: Здание
 Адрес: Калинина, 95 --------- Вид объекта: Здание
 Адрес: М- Амурского, 42 --------- Вид объекта: Здание
 Адрес: Советская, 27 --------- Вид объекта: Здание
 Адрес: Советская, 26 --------- Вид объекта: Здание
 Адрес: Воронежская, 154 --------- Вид объекта: Здание
 Адрес: М-Амурского, 21 --------- Вид объекта: Здание
 Адрес: М-Амурского, 42 --------- Вид объекта: Здание
 Адрес: РКЦ Комсомольск-на-Амуре, пр. Первостроителей, 19 --------- Вид объекта: Здание
 Адрес: Советская, 26 --------- Вид объекта: Здание
 Адрес: Воронежская, 154 --------- Вид объекта: Здание
 Адрес: М- Амурского, 21 --------- Вид объекта: Здание
 Адрес: М- Амурского, 42 --------- Вид объекта: Здание
 Адрес: РКЦ Комсомольск-на-Амуре,пр. Первостроителей, 19 --------- Вид объекта: Здание
 Адрес: Комсомольск -на- Амуре, пр. Первостроителей, 19 --------- Вид объекта: Здание
 Адрес: Воронежская, 154 --------- Вид объекта: Здание
 Адрес: М-Амурского, 42 --------- Вид объекта: Здание
 Адрес: Советская, 26 --------- Вид объекта: Здание
 Адрес: Южно-Сахалинск, Коммунистический пр-т, д. 47 --------- Вид объекта: Здание
 Адрес: Карла Маркса, д. 16 --------- Вид объекта: Здание
 Адрес: Южно-Сахалинск, Коммунистический пр-т, д. 47 --------- Вид объекта: Здание
 Адрес: Карла Маркса, д. 16 --------- Вид объекта: Здание
 Адрес: Южно-Сахалинск, Коммунистический пр-т, д. 47 --------- Вид объекта: Здание
 Адрес: Южно-Сахалинск, Коммунистический пр-т, д. 47 --------- Вид объекта: Здание
 Адрес: Кирова,17 --------- Вид объекта: Здание
 Адрес: 50 лет Советской Армии, 31/7 --------- Вид объекта: Здание
 Адрес: Покровск --------- Вид объекта: Здание
 Адрес: Ленина, 70 --------- Вид объекта: Здание
 Адрес: РКЦ Нерюнгри --------- Вид объекта: Здание
 Адрес: Ленина, 22 --------- Вид объекта: Здание
 Адрес: 50 лет Советской Армии, 31/7 --------- Вид объекта: Здание
 Адрес: Покровск --------- Вид объекта: Здание
 Адрес: Ленина, 70 --------- Вид объекта: Здание
 Адрес: РКЦ Нерюнгри --------- Вид объекта: Здание
 Адрес: Ленина, 22 --------- Вид объекта: Здание
 Адрес: Покровск --------- Вид объекта: Здание
 Адрес: Ленина, 70 --------- Вид объекта: Здание
 Адрес: РКЦ Нерюнгри --------- Вид объекта: Здание
 Адрес: Кирова,17 --------- Вид объекта: Здание
 Адрес: Покровск --------- Вид объекта: Здание
 Адрес: Ленина,70 --------- Вид объекта: Здание
 Адрес: РКЦ Нерюнгри --------- Вид объекта: Здание
 Адрес: Кирова, 17 --------- Вид объекта: Здание
 Адрес: Покровск --------- Вид объекта: Здание
 Адрес: Кирова,17 --------- Вид объекта: Здание
 Адрес: Светланская, 71 --------- Вид объекта: буфет
 Адрес: Светланская, 73 --------- Вид объекта: столовая
 Адрес: Светланская, 71 --------- Вид объекта: буфет
 Адрес: Светланская, 73 --------- Вид объекта: столовая
 Адрес: Светланская,73 --------- Вид объекта: столовая
 Адрес: Светланская,71 --------- Вид объекта: буфет
 Адрес: Светланская, 71 --------- Вид объекта: буфет
 Адрес: Светланская, 73 --------- Вид объекта: столовая
 Адрес: Верхнепортовая, 44 --------- Вид объекта: Здание
 Адрес: Верхнепортовая, 44 --------- Вид объекта: Здание
 Адрес: Верхнепортовая, 44 --------- Вид объекта: Здание
 Адрес: Верхнепортовая, 44 --------- Вид объекта: Здание
 Адрес: Верхнепортовая, 44 --------- Вид объекта: Здание
 Адрес: пр. К/Маркса 29/2 --------- Вид объекта: Здание
 Адрес: Воронежская, 154 --------- Вид объекта: Здание
 Адрес: Муравьева-Амурского, 21 --------- Вид объекта: Здание
 Адрес: Муравьева-Амурского, 42 --------- Вид объекта: Здание
 Адрес: Воронежская, 154 --------- Вид объекта: Здание
 Адрес: Муравьева-Амурского, 21 --------- Вид объекта: Здание
 Адрес: Муравьева-Амурского, 42 --------- Вид объекта: Здание
 Адрес: Воронежская, 154 --------- Вид объекта: Здание
 Адрес: Муравьева-Амурского, 21 --------- Вид объекта: Здание
 Адрес: Муравьева-Амурского, 42 --------- Вид объекта: Здание
 Адрес: Воронежская, 154 --------- Вид объекта: Здание
 Адрес: Муравьева-Амурского, 42 --------- Вид объекта: Здание
 Адрес: Воронежская, 154 --------- Вид объекта: Здание
 Адрес: Муравьева-Амурского, 21 --------- Вид объекта: Здание
 Адрес: Муравьева-Амурского, 42 --------- Вид объекта: Здание

In [13]:
# Выведите уникальные значения
for value in df['Направление расходов'].unique():
    print(value)

Калинина,261
Седова, 23
Светланская,111
Находка, Находкинский пр-т, 13
Фонтанная,19
Семеновская,29а
Мордовцева,6
Светланская,69
Светланская,71
Светланская,73
Светланская,73А
Океанский пр-т, 34
Пушкинская, 8Б
Некрасова, 102
Пушкина,59
Ленина, 64
Находка, Находкинский пр-т,13
Калинина, 261
Пушкинская,8б
Светланская,71-
Светланская,73А
Фонтанная, 19
пр-т 50 лет Октября,89
Ленина,64
Пушкина, 59
Мордовцева, 6
Светланская, 69
Светланская, 71
Светланская, 73 А
Фонтанная, 19
Некрасова,102
Горького 7
Дежнева, 7
Южная
Колхозная 32 Б
п. Эгвекинот
Билибино
Горького, 7
Дежнева 7
пгт.Эгвекинот
пгт. Эгвекинот
Биробиджан, пр-т 60-летия СССР, 5
Чапаева,5А
Чапаева, 5А
Богдана Хмельницкого 52/2
Профсоюзная, д.12
Ленина, 29
Благовещенск, пер.Святителя Иннокентия, 17
Зея пер.Жуковский,15
Благовещенск, пер. Святителя Иннокентия,17
Профсоюзная, 12
Ленина 29
Зея, пер.Жуковский,15
Богдана Хмельницкого, 52/2
Профсоюзная,12
Пушкина, 4
Пушкина,6
К.Маркса,36-20, кв.29
К.Маркса 36-20, кв.29
Поротова, 14
Ленинская, 33
Партизанская, 11
Ленинская, 22
пр. Карла Маркса, 29/2
пр. К/Маркса 29/2
Ленинская 22
РКЦ Комсомольск-на-Амуре, пр. Первостроителей, 19
Советская, 26
Воронежская, 154
М-Амурского, 42
М-Амурского, 21
Калинина, 95
ул, Воронежская, 154
М- Амурского, 21
М- Амурского, 42
Советская, 27
РКЦ Комсомольск-на-Амуре,пр. Первостроителей, 19
Комсомольск -на- Амуре, пр. Первостроителей, 19
Южно-Сахалинск, Коммунистический пр-т, д. 47
Карла Маркса, д. 16
Кирова,17
50 лет Советской Армии, 31/7
Покровск
Ленина, 70
РКЦ Нерюнгри
Ленина, 22
Ленина,70
Кирова, 17
Светланская, 73
Верхнепортовая, 44
Муравьева-Амурского, 21
Муравьева-Амурского, 42

In [14]:
print(len(df['Направление расходов']))

228

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 228 entries, 0 to 250
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Наименование вида расходов  228 non-null    object
 1   Направление расходов        228 non-null    object
 2   Вид объекта                 228 non-null    object
 3   Дата проведения             228 non-null    object
 4   Конечный остаток            228 non-null    float64
dtypes: float64(1), object(4)
memory usage: 18.8+ KB

In [16]:
df.head()

,Наименование вида расходов,Направление расходов,Вид объекта,Дата проведения,Конечный остаток
0,Расходы по оплате потребления электроэнергии,"Калинина,261",Здание,31.12.2020,32790.96
1,Расходы по оплате потребления электроэнергии,"Седова, 23",Здание,31.12.2020,2274.13
2,Расходы по оплате потребления электроэнергии,"Светланская,111",Здание,31.12.2020,238482.63
3,Расходы по оплате потребления электроэнергии,"Находка, Находкинский пр-т, 13",Здание,31.12.2020,614813.95
4,Расходы по оплате потребления электроэнергии,"Фонтанная,19",Здание,31.12.2020,22413.58

In [17]:
type_JKY.head()

0    134.1100.010000 Плата за технологическое присоединение к электрическим сетям г. Владивосток ул. Калинина,261
1                                    Оплата за электроэнергию по тарифам  зд.  Вл-Александровское, ул. Седова, 23
2                                                      Оплата за электроэнергию по тарифам зд. ул.Светланская,111
3                                        Оплата за электроэнергию по тарифам зд. г.Находка, Находкинский пр-т, 13
4                                                  Оплата за электроэнергию по тарифам  зд. Склад ул.Фонтанная,19
Name: Направление расходов, dtype: object

In [18]:
# Выведите уникальные значения
for value in type_JKY.unique():
    print(value)

134.1100.010000 Плата за технологическое присоединение к электрическим сетям г. Владивосток ул. Калинина,261
Оплата за электроэнергию по тарифам  зд.  Вл-Александровское, ул. Седова, 23
Оплата за электроэнергию по тарифам зд. ул.Светланская,111
Оплата за электроэнергию по тарифам зд. г.Находка, Находкинский пр-т, 13
Оплата за электроэнергию по тарифам  зд. Склад ул.Фонтанная,19
Оплата за электроэнергию по тарифам  зд. Убежище ул.Семеновская,29а
Оплата за электроэнергию по тарифам  зд. ул.Калинина,261
Оплата за электроэнергию по тарифам зд. ул.Мордовцева,6
Оплата за электроэнергию по тарифам зд. ул.Светланская,69
Оплата за электроэнергию по тарифам зд. ул.Светланская,71
Оплата за электроэнергию по тарифам зд. ул.Светланская,71 Пристройка
Оплата за электроэнергию по тарифам зд. ул.Светланская,73
Оплата за электроэнергию по тарифам зд. ул.Светланская,73А
Оплата за электроэнергию по тарифам зд. Океанский пр-т, 34
Оплата за электроэнергию по тарифам зд. ул.Пушкинская, 8Б
Оплата за электроэнергию по тарифам зд. г.Уссурийск, ул.Некрасова, 102
Оплата за электроэнергию по тарифам зд. с.Вольно-Надеждинское, ул.Пушкина,59
Оплата за электроэнергию по тарифам зд. г.Дальнереченск, ул.Ленина, 64
Оплата за тепловую энергию по тарифам зд. г.Находка, Находкинский пр-т,13
Оплата за тепловую энергию по тарифам зд. г.Уссурийск, ул.Некрасова, 102 ( гараж на 10 а/м)
Оплата за тепловую энергию по тарифам зд. г.Уссурийск, ул.Некрасова, 102(осн. здание)
Оплата за тепловую энергию по тарифам зд. с.Вольно-Надеждинское, ул.Пушкина,59
Оплата за тепловую энергию по тарифам зд. ул.Калинина, 261
Оплата за тепловую энергию по тарифам зд. ул.Пушкинская,8б
Оплата за тепловую энергию по тарифам зд. ул.Мордовцева,6
Оплата за тепловую энергию по тарифам зд. ул.Светланская,69
Оплата за тепловую энергию по тарифам зд. ул.Светланская,71
Оплата за тепловую энергию по тарифам зд. ул.Светланская,71-Пристройка
Оплата за тепловую энергию по тарифам зд. ул.Светланская,73
Оплата за тепловую энергию по тарифам зд. ул.Светланская,73А -  ст.134.1100
Оплата за тепловую энергию по тарифам зд. ул.Фонтанная, 19 -  ст.134.1100
Оплата за тепловую энергию по тарифам зд.Океанский пр-т, 34
Оплата за тепловую энергию по тарифам зд. ул.Светланская,111
Оплата за тепловую энергию по тарифам г. Дальнегорск, ул. пр-т 50 лет Октября,89
Оплата за тепловую энергию по тарифам г. Дальнереченск, ул. Ленина,64
Оплата за водоотведение по тарифам зд. ул.Светланская,111
Оплата за водоотведение по тарифам зд. г.Находка, Находкинский пр-т, 13
Оплата за водоотведение по тарифам зд. г.Уссурийск, ул.Некрасова, 102
Оплата за водоотведение по тарифам зд. г.Уссурийск, ул.Некрасова, 102 (ГАРАЖ на 10 автомобилей)
Оплата за водоотведение по тарифам зд. Океанский пр-т, 34
Оплата за водоотведение по тарифам зд. с.Вольно-Надеждинское, ул.Пушкина, 59
Оплата за водоотведение по тарифам зд. ул.Калинина, 261
Оплата за водоотведение по тарифам зд. ул.Мордовцева, 6
Оплата за водоотведение по тарифам зд. ул.Светланская, 69
Оплата за водоотведение по тарифам зд. ул.Светланская, 71
Оплата за водоотведение по тарифам зд. ул.Светланская, 71 Пристройка
Оплата за водоотведение по тарифам зд. ул.Светланская, 73 А
Оплата за водоотведение по тарифам зд. ул.Фонтанная, 19
Оплата за холодное водоснабжение по тарифам зд. ул.Светланская,111
Оплата за холодное водоснабжение по тарифам зд. г.Находка, Находкинский пр-т, 13
Оплата за холодное водоснабжение по тарифам зд. г.Уссурийск, ул.Некрасова,102
Оплата за холодное водоснабжение по тарифам зд. г.Уссурийск, ул.Некрасова,102 (ГАРАЖ на 10 автомобилей)
Оплата за холодное водоснабжение по тарифам зд. Океанский пр-т, 34
Оплата за холодное водоснабжение по тарифам зд. с.Вольно-Надеждинское,  ул.Пушкина,59
Оплата за холодное водоснабжение по тарифам зд. ул.Калинина, 261
Оплата за холодное водоснабжение по тарифам зд. ул.Мордовцева,6
Оплата за холодное водоснабжение по тарифам зд. ул.Светланская, 69
Оплата за холодное водоснабжение по тарифам зд. ул.Светланская, 71
Оплата за холодное водоснабжение по тарифам зд. ул.Светланская, 71 Пристройка
Оплата за холодное водоснабжение по тарифам зд. ул.Светланская, 73 А
Оплата за холодное водоснабжение по тарифам зд. ул.Фонтанная, 19
Другие расходы прошлых лет, выявленные в текущем году. Расходы на коммунальные услуги
134.1100.010000 Оплата за электроэнергию по тарифам зд. г. Анадырь, ул. Горького 7 дизель-генераторная установка
134.1100.010000 Оплата за электроэнергию по тарифам зд. г. Анадырь, ул. Дежнева, 7
134.1100.010000 Оплата за электроэнергию по тарифам г. Анадырь, ул. Южная (гараж)
134.1100.010000 Оплата за электроэнергию по тарифам зд. г. Анадырь, ул. Горького 7
134.1100.010000 Оплата за электроэнергию по тарифам г.Анадырь, ул. Колхозная 32 Б (склад)
134.1100.010000 Оплата за электроэнергию по тарифам зд. п. Эгвекинот
134.1100.010000 Оплата за электроэнергию по тарифам зд. г. Билибино
134.1100.010000 Плата за технологическое присоединение к электрическим сетям г. Анадырь, ул. Горького, 7
Оплата за тепловую энергию по тарифам зд. г. Анадырь, ул. Дежнева 7
Оплата за тепловую энергию по тарифам зд. г. Анадырь, ул. Колхозная 32 Б
Оплата за тепловую энергию по тарифам зд. г. Анадырь, ул. Южная (гараж)
Оплата за тепловую энергию по тарифам зд. г. Билибино
Оплата за тепловую энергию по тарифам зд. пгт.Эгвекинот
Оплата за водоотведение по тарифам зд. г. Анадырь, ул. Дежнева 7
Оплата за водоотведение по тарифам здание (гараж) г. Анадырь, ул. Южная
Оплата за водоотведение по тарифам зд. г. Билибино
Оплата за водоотведение по тарифам зд. пгт. Эгвекинот
Оплата за горячее водоснабжение  по тарифам здание (гараж) г. Анадырь, ул. Южная
Оплата за горячее водоснабжение по тарифам зд. г. Анадырь, ул. Дежнева 7
Оплата за горячее водоснабжение по тарифам зд. РКЦ  г. Билибино
Оплата за горячее водоснабжение по тарифам зд. пгт.Эгвекинот
Оплата за холодное водоснабжение по тарифам зд. г. Анадырь, ул. Дежнева 7
Оплата за холодное водоснабжение по тарифам зд. г. Анадырь, ул. Южная (гараж)
Оплата за холодное водоснабжение по тарифам зд. г. Билибино
Оплата за холодное водоснабжение по тарифам зд. пгт.Эгвекинот
Оплата за электроэнергию  по тарифам г.Биробиджан, пр-т 60-летия СССР, 5
Оплата за электроэнергию по тарифам г.Биробиджан, ул.Чапаева,5А
Оплата за тепловую энергию по тарифам г.Биробиджан, пр-т 60-летия СССР, 5
Оплата за тепловую энергию  по тарифам г.Биробиджан, ул.Чапаева, 5А
Оплата за холодное водоснабжение по тарифам г.Биробиджан, пр-т 60-летия СССР, 5
Оплата за холодное водоснабжение по тарифам г.Биробиджан,ул.Чапаева, 5А
Оплата за водоотведение  по тарифам г.Биробиджан, пр-т 60-летия СССР, 5
Оплата за водоотведение по тарифам г.Биробиджан, ул.Чапаева, 5А
Оплата за электроэнергию по тарифам г.Благовещенск, пер.Святителя Иннокентия, 17, Административное здание
Оплата за электроэнергию по тарифам г.Благовещенск, ул.Богдана Хмельницкого 52/2
Оплата за электроэнергию по тарифам г.Зея пер.Жуковский,15, Административное здание
Оплата за электроэнергию по тарифам г.Тында ул.Профсоюзная, д.12
Оплата за электроэнергию по тарифам пгт Магдагачи, ул.Ленина, 29
Оплата за электроэнергию по тарифам г.Благовещенск, пер.Святителя Иннокентия, 17, Администр. зд. (Пристройка)
Оплата за электроэнергию по тарифам г.Благовещенск, пер.Святителя Иннокентия, 17, Пристройка к зданию (Новая)
Оплата за электроэнергию по тарифам г.Благовещенск, пер.Святителя Иннокентия, 17, Гараж
Оплата за электроэнергию по тарифам г.Благовещенск, пер.Святителя Иннокентия, 17, Помещение Объект №2
Оплата за электроэнергию по тарифам г.Зея пер.Жуковский,15, Гараж
Оплата за тепловую энергию по тарифам г.Благовещенск, пер. Святителя Иннокентия,17,  Административное здание
Оплата за тепловую энергию по тарифам г.Благовещенск, пер. Святителя Иннокентия,17, Администр.зд. (Пристройка)
Оплата за тепловую энергию по тарифам г.Благовещенск, пер. Святителя Иннокентия,17, Гараж
Оплата за тепловую энергию по тарифам г.Благовещенск, пер. Святителя Иннокентия,17, Помещение объект №2
Оплата за тепловую энергию по тарифам г.Благовещенск, пер. Святителя Иннокентия,17, Пристройка к зданию (Новая)
Оплата за тепловую энергию по тарифам г.Благовещенск, ул.Богдана Хмельницкого 52/2, Административное здание
Оплата за тепловую энергию по тарифам г.Благовещенск, ул.Богдана Хмельницкого 52/2, Контрольно-пропускной пункт
Оплата за тепловую энергию по тарифам г.Зея, пер.Жуковский,15, Административное здание
Оплата за тепловую энергию по тарифам г.Тында ул. Профсоюзная, 12
Оплата за тепловую энергию по тарифам пгт. Магдагачи, ул. Ленина 29
Оплата за тепловую энергию по тарифам г.Зея, пер.Жуковский,15, Гараж
Оплата за холодное водоснабжение по тарифам г.Благовещенск, пер.Святителя Иннокентия, 17,  Административное здание
Оплата за холодное водоснабжение по тарифам г.Благовещенск, пер.Святителя Иннокентия, 17, Администр.зд. (Пристройка)
Оплата за холодное водоснабжение по тарифам г.Благовещенск, пер.Святителя Иннокентия, 17, Гараж
Оплата за холодное водоснабжение по тарифам г.Благовещенск, пер.Святителя Иннокентия, 17, Пристройка к зданию (новая)
Оплата за холодное водоснабжение по тарифам г.Благовещенск, ул.Богдана Хмельницкого, 52/2, Административное здание
Оплата за холодное водоснабжение по тарифам г.Благовещенск, ул.Богдана Хмельницкого, 52/2, Контрольно-пропускной пункт
Оплата за холодное водоснабжение по тарифам г.Тында, ул.Профсоюзная,12
Оплата за водоотведение по тарифам г.Благовещенск, пер.Святителя Иннокентия, 17,  Административное здание
Оплата за водоотведение по тарифам г.Благовещенск, пер.Святителя Иннокентия, 17, Администр.зд. (Пристройка)
Оплата за водоотведение по тарифам г.Благовещенск, пер.Святителя Иннокентия, 17, Пристройка к зданию (новая)
Оплата за водоотведение по тарифам г.Благовещенск, ул.Богдана Хмельницкого, 52/2, Административное здание
Оплата за водоотведение по тарифам г.Благовещенск, ул.Богдана Хмельницкого, 52/2, Контрольно-пропускной пункт
Оплата за водоотведение по тарифам г.Тында, ул.Профсоюзная,12
Оплата за горячее водоснабжение по тарифам РКЦ Тында ул. Профсоюзная, 12
Оплата за электроэнергию по тарифам здание г. Магадан, ул.Пушкина, 4
Оплата за тепловую энергию по тарифам здание г. Магадан, ул.Пушкина,6 (Гараж)
Оплата за тепловую энергию по тарифам здание г. Магадан, ул.Пушкина, 4
Оплата за тепловую энергию по тарифам здание г. Магадан, ул.К.Маркса,36-20, кв.29
Оплата за горячее водоснабжение по тарифам здание ул.Пушкина, 4
Оплата за горячее водоснабжение по тарифам здание г. Магадан, ул. К.Маркса 36-20, кв.29
Оплата за холодное водоснабжение по тарифам здание ул.Пушкина, 4
Оплата за водоотведение по тарифам здание ул.Пушкина, 4
Оплата за электроэнергию по тарифам зд. пгт. Палана ул. Поротова, 14
Оплата за электроэнергию по тарифам зд.  РКЦ Мильково ул. Ленинская, 33
Оплата за электроэнергию по тарифам зд. с. Тигиль ул. Партизанская, 11
Оплата за электроэнергию по тарифам зд.  ул. Ленинская, 22
Оплата за электроэнергию по тарифам зд.  пр. Карла Маркса, 29/2
134.1100.020000 Оплата за дизельное топливо зд. пр. К/Маркса 29/2
134.1100.020000 Оплата за дизельное топливо зд. ул. Ленинская 22
134.1100.020000 Оплата за дизельное топливо зд. РКЦ Мильково, ул. Ленинская, 33
Оплата за тепловую энергию по тарифам зд.  пгт. Палана ул. Поротова, 14
Оплата за тепловую энергию по тарифам зд. РКЦ Мильково, ул. Ленинская, 33
Оплата за тепловую энергию по тарифам зд. с. Тигиль ул. Партизанская, 11
Оплата за тепловую энергию по тарифам зд. ул. Ленинская, 22
Оплата за водоотведение по тарифам зд. пгт. Палана ул. Поротова, 14
Оплата за водоотведение по тарифам зд. РКЦ Мильково ул. Ленинская, 33
Оплата за водоотведение по тарифам зд. ул. Ленинская, 22
Оплата за водоотведение по тарифам зд. пр. Карла Маркса, 29/2
Оплата за горячее водоснабжение по тарифам РКЦ Мильково ул. Ленинская, 33
Оплата за холодное водоснабжение по тарифам зд. пгт. Палана ул. Поротова, 14
Оплата за холодное водоснабжение по тарифам зд. РКЦ Мильково ул. Ленинская, 33
Оплата за холодное водоснабжение по тарифам зд. с. Тигиль ул. Партизанская, 11
Оплата за холодное водоснабжение по тарифам зд. ул. Ленинская, 22
Оплата за холодное водоснабжение по тарифам зд. пр. Карла Маркса, 29/2
Оплата за  электроэнергию по тарифам РКЦ Комсомольск-на-Амуре, пр. Первостроителей, 19
Оплата за электроэнергию по тарифам РКЦ Советская Гавань,  ул. Советская, 26
Оплата за электроэнергию по тарифам зд. ул. Воронежская, 154
Оплата за электроэнергию по тарифам зд. ул. М-Амурского, 42
Оплата за электроэнергию по тарифам зд. ул.М-Амурского, 21
Оплата за электроэнергию по тарифам зд. с. Троицкое, ул. Калинина, 95
Оплата за  тепловую энергию по тарифам РКЦ Комсомольск-на-Амуре, пр. Первостроителей, 19
Оплата за тепловую энергию по тарифам зд. ул, Воронежская, 154
Оплата за тепловую энергию по тарифам зд. ул. М- Амурского, 21
Оплата за тепловую энергию по тарифам зд. ул. М- Амурского, 42
Оплата за тепловую энергию по тарифам РКЦ Советская Гавань, ул. Советская, 26
Оплата за тепловую энергию по тарифам с. Троицкое, ул. Калинина, 95
Оплата за тепловую энергию по тарифам здание гараж Советская Гавань, ул. Советская, 27
Оплата за водоотведение по тарифам РКЦ Советская Гавань,  ул. Советская, 26
Оплата за  водоотведение по тарифам зд. ул. Воронежская, 154
Оплата за  водоотведение по тарифам зд. ул. М-Амурского, 21
Оплата за  водоотведение по тарифам зд. ул. М-Амурского, 42
Оплата за  водоотведение по тарифам РКЦ Комсомольск-на-Амуре, пр. Первостроителей, 19
Оплата за холодное водоснабжение по тарифам РКЦ Советская Гавань, ул. Советская, 26
Оплата за холодное водоснабжение по тарифам зд. ул. Воронежская, 154
Оплата за холодное водоснабжение по тарифам зд. ул. М- Амурского, 21
Оплата за холодное водоснабжение по тарифам зд. ул. М- Амурского, 42
Оплата за холодное водоснабжение по тарифам РКЦ Комсомольск-на-Амуре,пр. Первостроителей, 19
Оплата за  горячее водоснабжение по тарифам зд. Комсомольск -на- Амуре, пр. Первостроителей, 19
Оплата за горячее водоснабжение по тарифам зд. ул. Воронежская, 154
Оплата за горячее водоснабжение по тарифам зд. ул. М-Амурского, 42
Оплата за горячее водоснабжение по тарифам РКЦ Советская Гавань, ул. Советская, 26
Расходы по оплате потребления электроэнергии, г. Южно-Сахалинск, Коммунистический пр-т, д. 47
Расходы по оплате потребления электроэнергии, г. Южно-Сахалинск, ул. Карла Маркса, д. 16
Расходы по оплате потребления электроэнергии РКЦ Курильск
Расходы по оплате отопления, г. Южно-Сахалинск, Коммунистический пр-т, д. 47
Расходы по оплате отопления, г. Южно-Сахалинск, ул. Карла Маркса, д. 16
Расходы по оплате отопления РКЦ Курильск
Расходы по приобретению дизельного топлива (отопление) РКЦ Курильск
Расходы по оплате водоотведения, г. Южно-Сахалинск, Коммунистический пр-т, д. 47
Расходы по оплате водоотведения РКЦ Курильск
Расходы по оплате холодного водоснабжения, г. Южно-Сахалинск, Коммунистический пр-т, д. 47
Расходы по оплате холодного водоснабжения РКЦ Курильск
Оплата за электроэнергию по тарифам здание г.Якутск,  ул.Кирова,17
Оплата за электроэнергию по тарифам часть жилого здания г.Якутск, ул.50 лет Советской Армии, 31/7
Оплата за электроэнергию по тарифам здание  г.Покровск
Оплата за электроэнергию по тарифам здание РКЦ Ленск, ул.Ленина, 70
Оплата за электроэнергию по тарифам здание  РКЦ Нерюнгри
Оплата за электроэнергию по тарифам здание г.Якутск, (Гараж)  ул.Ленина, 22
Оплата за тепловую энергию по тарифам часть жилого здания г.Якутск, ул.50 лет Советской Армии, 31/7
Оплата за тепловую энергию по тарифам здание г. Покровск
Оплата за тепловую энергию по тарифам здание РКЦ Ленск, ул.Ленина, 70
Оплата за тепловую энергию по тарифам здание РКЦ Нерюнгри
Оплата за тепловую энергию по тарифам здание г.Якутск,  ул.Ленина, 22
Оплата за холодное водоснабжение по тарифам здание г.Покровск
Оплата за холодное водоснабжение по тарифам зд. РКЦ Ленск, ул.Ленина, 70
Оплата за холодное водоснабжение по тарифам здание РКЦ Нерюнгри
Оплата за холодное водоснабжение по тарифам здание г.Якутск,  ул.Кирова,17
Оплата за горячее водоснабжение по тарифам здание г.Покровск
Оплата за  водоотведение по тарифам здание РКЦ Ленск, ул.Ленина,70
Оплата за водоотведение по тарифам здание РКЦ Нерюнгри
Оплата за  водоотведение  по тарифам здание г.Якутск,  ул.Кирова, 17
Оплата за водоотведение по тарифам здание г.Покровск
Оплата потребления газа по тарифам зд. ул.Кирова,17
Оплата за электроэнергию по тарифам г. Влад-к, ул. Светланская, 71 (Буфет)
Оплата за электроэнергию по тарифам г. Влад-к, ул. Светланская, 73 (Столовая)
Оплата за тепловую энергию по тарифам ул. Светланская, 71 (Буфет)
Оплата за тепловую энергию по тарифам ул. Светланская, 73 (Столовая)
134.11100.03000 Расходы по оплате услуг за холодное водоснабжение по тарифам ул. Светланская,73 (столовая)
134.1100.030000 расходы по оплате услуг за холодное водоснабжение по тарифам ул. Светланская,71 (буфет)
Оплата за водоотведение по тарифам г. Влад-к, ул. Светланская, 71 (Буфет)
Оплата за водоотведение по тарифам г. Влад-к, ул. Светланская, 73  (Столовая)
Оплата за электроэнергию по тарифам зд. ул.Верхнепортовая, 44
Оплата за тепловую энергию по тарифам зд. ул.Верхнепортовая, 44
Оплата за водоотведение по тарифам зд. ул.Верхнепортовая, 44
Оплата за холодное водоснабжение по тарифам зд. ул.Верхнепортовая, 44
Оплата за горячее водоснабжение по тарифам зд. ул.Верхнепортовая, 44
Оплата за электроэнергию по тарифам
Оплата за водоотведение по тарифам
Оплата за холодное водоснабжение по тарифам
Оплата за электроэнергию по тарифам ул. Воронежская, 154
Оплата за электроэнергию по тарифам ул. Муравьева-Амурского, 21
Оплата за электроэнергию по тарифам ул. Муравьева-Амурского, 42
Оплата за тепловую энергию по тарифам ул. Воронежская, 154
Оплата за тепловую энергию по тарифам ул. Муравьева-Амурского, 21
Оплата за тепловую энергию по тарифам ул. Муравьева-Амурского, 42
Оплата за водоотведение по тарифам, ул. Воронежская, 154
Оплата за водоотведение по тарифам, ул. Муравьева-Амурского, 21
Оплата за водоотведение по тарифам, ул. Муравьева-Амурского, 42
Оплата за горячее  водоснабжение по тарифам, ул. Воронежская, 154
Оплата за горячее  водоснабжение по тарифам, ул. Муравьева-Амурского, 42
Оплата за холодное водоснабжение по тарифам, ул. Воронежская, 154
Оплата за холодное водоснабжение по тарифам, ул. Муравьева-Амурского, 21
Оплата за холодное водоснабжение по тарифам, ул. Муравьева-Амурского, 42

In [19]:
def replace_words_in_column(column, replacement_dict):
    new_column = column.copy()
    for search_word, replace_word in replacement_dict.items():
        new_column = new_column.apply(lambda x: replace_word if search_word in x else x)
    return new_column


replacement_dict = {'Оплата за водоотведение по тарифам': 'ВО',
                    'Оплата водоотведения по тарифам': 'ВО',
                    'Оплата за  водоотведение по тарифам': 'ВО',
                    'Оплата за горячее водоснабжение по тарифам': 'ГВС',
                    'Оплата за тепловую энергию по тарифам': 'ТЭ',
                    'Оплата за холодное водоснабжение по тарифам': 'ХВС',
                    'Оплата за электроэнергию по тарифам': 'ЭЭ',
                    'Оплата за холодное водоснабжение  по тарифам': 'ХВС',
                    'Оплата за дизельное топливо': 'ДТ',
                    'Оплата потребления газа по тарифам': 'ПГ',
                    'Плата за технологическое присоединение к электрическим сетям': 'ТПЭС',
                    'Другие расходы': 'ДР',
                    'Оплата за горячее  водоснабжение по тарифам': 'ГВС',
                    'Оплата за эектроэнергию по тарифам': 'ЭЭ',
                    'Оплата за  горячее водоснабжение по тарифам': 'ГВС',
                    'Оплата за  тепловую энергию по тарифам': 'ТЭ',
                    'Оплата за  электроэнергию по тарифам': 'ЭЭ',
                    'Оплата за горячее водоснабжение  по тарифам здание (гараж': 'ГВС',
                    'Оплата за электроэнергию  по тарифам': 'ЭЭ',
                    'Оплата за тепловую энергию  по тарифам': 'ЭЭ',
                    'Оплата за водоотведение  по тарифам': 'ВО',
                    'Расходы по оплате потребления электроэнергии': 'ПЭ',
                    'Расходы по оплате отопления': 'О',
                    'Оплата за водоотведение  по тарифам': 'ВО',
                    'Расходы по приобретению дизельного топлива': 'ДТ',
                    'Расходы по оплате водоотведения': 'ВО',
                    'Оплата за водоотведение  по тарифам': 'ВО',
                    'Расходы по оплате холодного водоснабжения': 'ХВС',
                    'Расходы по оплате услуг за холодное водоснабжение по тарифам': 'ХВС',
                    'расходы по оплате услуг за холодное водоснабжение по тарифа': 'ХВС',
                    'Оплата за  водоотведение  по тарифам': 'ВО',
                   }
type_JKY = replace_words_in_column(type_JKY, replacement_dict)

# Выведите уникальные значения
for value in type_JKY.unique():
    print(value)

ТПЭС
ЭЭ
ТЭ
ВО
ХВС
ДР
ГВС
ДТ
ПЭ
О
ПГ

In [20]:
def replace_column(dataframe, column_name, new_values):
    dataframe[column_name] = new_values
    return dataframe

df = replace_column(df, 'Наименование вида расходов', type_JKY)

df.head()

,Наименование вида расходов,Направление расходов,Вид объекта,Дата проведения,Конечный остаток
0,ТПЭС,"Калинина,261",Здание,31.12.2020,32790.96
1,ЭЭ,"Седова, 23",Здание,31.12.2020,2274.13
2,ЭЭ,"Светланская,111",Здание,31.12.2020,238482.63
3,ЭЭ,"Находка, Находкинский пр-т, 13",Здание,31.12.2020,614813.95
4,ЭЭ,"Фонтанная,19",Здание,31.12.2020,22413.58

In [21]:
def swap_columns(dataframe, column1, column2):
    dataframe[column1], dataframe[column2] = dataframe[column2].copy(), dataframe[column1].copy()
    dataframe.rename(columns={column1: column2, column2: column1}, inplace=True)
    return dataframe

df = swap_columns(df, 'Направление расходов', 'Наименование вида расходов')

df.head()

,Направление расходов,Наименование вида расходов,Вид объекта,Дата проведения,Конечный остаток
0,"Калинина,261",ТПЭС,Здание,31.12.2020,32790.96
1,"Седова, 23",ЭЭ,Здание,31.12.2020,2274.13
2,"Светланская,111",ЭЭ,Здание,31.12.2020,238482.63
3,"Находка, Находкинский пр-т, 13",ЭЭ,Здание,31.12.2020,614813.95
4,"Фонтанная,19",ЭЭ,Здание,31.12.2020,22413.58

In [22]:
# Сохранение файла в формате CSV с указанием кодировки UTF-8
df.to_csv('2020_new_обработанный_2.csv', index=False, encoding='Windows-1251')

# Сохранение в Excel
df.to_excel('2020_new_обработанный_2.xlsx', index=False)